// boneyard-js skeleton registry (generated by `npx boneyard-js build`).
//
// This placeholder keeps the app buildable before bones are generated.
// The CLI will overwrite this file with a generated registry.
export {};

